version: '3.8'
services:
  backend:
    build:
      context: ./backend/src
      dockerfile: ../../docker/Dockerfile.backend
    ports:
      - "5050:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - db
  db:
    image: postgres:16
    env_file:
      - .env
    ports:
      - "5432:5432"
