# Use official Node image
FROM node:20-alpine AS build
WORKDIR /app
COPY ../frontend ./
RUN npm install && npm run build

# Use nginx to serve the build
FROM nginx:alpine
WORKDIR /usr/share/nginx/html
COPY --from=build /app/dist .
EXPOSE 3000
CMD ["nginx", "-g", "daemon off;"]
